jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 17.x]

    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v4
        with:
          ref: develop
          token: ${{ secrets.PUSHMAINSECRET }}
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install packages
        run: npm install
      - run: npm ci
      - name: Build for production
        run: npx vite build

  push:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v4
        with:
          ref: develop
          token: ${{ secrets.PUSHMAINSECRET }}
          fetch-depth: 0
      - name: Push to main
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git checkout main
          git merge --no-ff develop
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PUSHMAINSECRET }}
